package org.openremote.controller.model.event

global org.openremote.controller.statuscache.CommandFacade execute;

rule "create state1 for fan speed"
when
  Level( source == "VirtThermoSensor", value > 0 && <= 10 )
then
  System.out.println("State1");
  execute.command("state", "a");
end

rule "create state2 for fan speed"
when
  Level( source == "VirtThermoSensor", value > 10 && <= 20 )
then
  System.out.println("State2");
  execute.command("state", "b");
end

rule "create state3 for fan speed"
when
  Level( source == "VirtThermoSensor", value > 20 && <= 30 )
then
  System.out.println("State3");
  execute.command("state", "c");
end